"""Add whisper_model field.

Revision ID: bc149e2ef65f
Revises: c5614ae0da1b
Create Date: 2025-11-16 20:44:54.919450

"""

from typing import Sequence

import sqlalchemy as sa  # noqa: F401

from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "bc149e2ef65f"
down_revision: str | None = "c5614ae0da1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add columns as nullable first
    op.add_column("transcription_job", sa.Column("whisper_model", sa.Text(), nullable=True))
    op.add_column("transcription_job", sa.Column("language", sa.String(length=10), nullable=True))
    op.add_column("transcription_job", sa.Column("language_probability", sa.Float(), nullable=True))

    # Step 2: Fill existing rows with default value for whisper_model
    op.execute("UPDATE transcription_job SET whisper_model = 'base' WHERE whisper_model IS NULL")

    # Step 3: Make whisper_model NOT NULL
    op.alter_column("transcription_job", "whisper_model", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transcription_job", "language_probability")
    op.drop_column("transcription_job", "language")
    op.drop_column("transcription_job", "whisper_model")
    # ### end Alembic commands ###
